#!/bin/sh
# [Gedit Tool]
# Name=Wordpress Search
# Shortcut=<Control><Alt>w
# Applicability=all
# Output=nothing
# Input=selection-document
# Save-files=nothing

xargs -I '{}' gnome-open 'http://wordpress.org/search/{}'

